# .github/workflows/environment-secrets.yml
name: Environment Secrets Demo

on:
  push:
    branches: [ master ]

jobs:
  use-env-secrets:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Use Production Environment Secret
        run: |
          # This assumes PRODUCTION_API_KEY is set in the "production" environment
          if [[ -n "$PRODUCTION_API_KEY" ]]; then
            echo "PRODUCTION_API_KEY is available for the production environment"
            echo "Key length: ${#PRODUCTION_API_KEY}"
            
            # Simulate using the key for deployment
            echo "Deploying to production environment..."
          else
            echo "PRODUCTION_API_KEY is not set - did you configure the environment?"
            exit 1
          fi
        env:
          PRODUCTION_API_KEY: ${{ secrets.PRODUCTION_API_KEY }}
