# .github/workflows/org-secrets.yml
name: Organization Secrets Demo

on:
  push:
    branches: [ master ]

jobs:
  use-org-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Access Organization Secret
        run: |
          # This assumes ORG_API_KEY is set at the organization level
          if [[ -n "$ORG_API_KEY" ]]; then
            echo "ORG_API_KEY is available"
            
            # Example of using an organization secret safely
            # curl -s -H "Authorization: Bearer $ORG_API_KEY" https://api.example.org/data
          else
            echo "ORG_API_KEY is not set - this is expected if not using an organization"
          fi
        env:
          ORG_API_KEY: ${{ secrets.ORG_API_KEY }}
      
      - name: Explain Secret Precedence
        run: |
          echo "Secret Precedence Rules:"
          echo "1. Repository secrets override organization secrets with the same name"
          echo "2. Environment secrets override repository and organization secrets"
          echo "3. Job-level secrets override step-level environment variables"
